// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gonibejopgsktrzewwpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbmliZWpvcGdza3RyemV3d3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NTU2NTgsImV4cCI6MjA1MTIzMTY1OH0._EWZ8z-qKn9TMDQZirzB70mZO5RzKh00l8QNtRLsucA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);